/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as DepenseRouteImport } from './routes/depense'
import { Route as DettesRouteImport } from './routes/dettes'
import { Route as EnveloppesRouteImport } from './routes/enveloppes'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as OutilsRouteImport } from './routes/outils'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as RevenuRouteImport } from './routes/revenu'
import { Route as SaisieRouteImport } from './routes/saisie'
import { Route as SauvegardeRouteImport } from './routes/sauvegarde'
import { Route as SynchronisationRouteImport } from './routes/synchronisation'
import { Route as ComptesIndexRouteImport } from './routes/comptes.index'
import { Route as ComptesCompteRouteImport } from './routes/comptes.$compte'
import { Route as ComptesActionRouteImport } from './routes/comptes.action'
import { Route as ComptesTransfertsRouteImport } from './routes/comptes.transferts'
import { Route as EnveloppesIndexRouteImport } from './routes/enveloppes.index'
import { Route as EnveloppesActionRouteImport } from './routes/enveloppes.action'
import { Route as EnveloppesBudgetisationRouteImport } from './routes/enveloppes.budgetisation'
import { Route as EnveloppesCategoriesRouteImport } from './routes/enveloppes.categories'
import { Route as EnveloppesChronologieRouteImport } from './routes/enveloppes.chronologie'
import { Route as EnveloppesClasserRouteImport } from './routes/enveloppes.classer'
import { Route as EnveloppesCreerRouteImport } from './routes/enveloppes.creer'
import { Route as EnveloppesDetailsRouteImport } from './routes/enveloppes.details'
import { Route as EnveloppesModifierRouteImport } from './routes/enveloppes.modifier'
import { Route as ComptesTransfertsIndexRouteImport } from './routes/comptes.transferts.index'
import { Route as ComptesTransfertsNouveauRouteImport } from './routes/comptes.transferts.nouveau'
import { Route as EnveloppesCategorieNomRouteImport } from './routes/enveloppes.categorie.$nom'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const DepenseRoute = DepenseRouteImport.update({
  id: '/depense',
  path: '/depense',
  getParentRoute: () => rootRouteImport,
} as any)
const DettesRoute = DettesRouteImport.update({
  id: '/dettes',
  path: '/dettes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnveloppesRoute = EnveloppesRouteImport.update({
  id: '/enveloppes',
  path: '/enveloppes',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsRoute = OutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenuRoute = RevenuRouteImport.update({
  id: '/revenu',
  path: '/revenu',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieRoute = SaisieRouteImport.update({
  id: '/saisie',
  path: '/saisie',
  getParentRoute: () => rootRouteImport,
} as any)
const SauvegardeRoute = SauvegardeRouteImport.update({
  id: '/sauvegarde',
  path: '/sauvegarde',
  getParentRoute: () => rootRouteImport,
} as any)
const SynchronisationRoute = SynchronisationRouteImport.update({
  id: '/synchronisation',
  path: '/synchronisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesIndexRoute = ComptesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComptesRoute,
} as any)
const ComptesCompteRoute = ComptesCompteRouteImport.update({
  id: '/$compte',
  path: '/$compte',
  getParentRoute: () => ComptesRoute,
} as any)
const ComptesActionRoute = ComptesActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => ComptesRoute,
} as any)
const ComptesTransfertsRoute = ComptesTransfertsRouteImport.update({
  id: '/transferts',
  path: '/transferts',
  getParentRoute: () => ComptesRoute,
} as any)
const EnveloppesIndexRoute = EnveloppesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesActionRoute = EnveloppesActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesBudgetisationRoute = EnveloppesBudgetisationRouteImport.update({
  id: '/budgetisation',
  path: '/budgetisation',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesCategoriesRoute = EnveloppesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesChronologieRoute = EnveloppesChronologieRouteImport.update({
  id: '/chronologie',
  path: '/chronologie',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesClasserRoute = EnveloppesClasserRouteImport.update({
  id: '/classer',
  path: '/classer',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesCreerRoute = EnveloppesCreerRouteImport.update({
  id: '/creer',
  path: '/creer',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesDetailsRoute = EnveloppesDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesModifierRoute = EnveloppesModifierRouteImport.update({
  id: '/modifier',
  path: '/modifier',
  getParentRoute: () => EnveloppesRoute,
} as any)
const ComptesTransfertsIndexRoute = ComptesTransfertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComptesTransfertsRoute,
} as any)
const ComptesTransfertsNouveauRoute =
  ComptesTransfertsNouveauRouteImport.update({
    id: '/nouveau',
    path: '/nouveau',
    getParentRoute: () => ComptesTransfertsRoute,
  } as any)
const EnveloppesCategorieNomRoute = EnveloppesCategorieNomRouteImport.update({
  id: '/categorie/$nom',
  path: '/categorie/$nom',
  getParentRoute: () => EnveloppesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/analyses': typeof AnalysesRoute
  '/comptes': typeof ComptesRouteWithChildren
  '/depense': typeof DepenseRoute
  '/dettes': typeof DettesRoute
  '/enveloppes': typeof EnveloppesRouteWithChildren
  '/journal': typeof JournalRoute
  '/outils': typeof OutilsRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/revenu': typeof RevenuRoute
  '/saisie': typeof SaisieRoute
  '/sauvegarde': typeof SauvegardeRoute
  '/synchronisation': typeof SynchronisationRoute
  '/comptes/$compte': typeof ComptesCompteRoute
  '/comptes/action': typeof ComptesActionRoute
  '/comptes/transferts': typeof ComptesTransfertsRouteWithChildren
  '/enveloppes/action': typeof EnveloppesActionRoute
  '/enveloppes/budgetisation': typeof EnveloppesBudgetisationRoute
  '/enveloppes/categories': typeof EnveloppesCategoriesRoute
  '/enveloppes/chronologie': typeof EnveloppesChronologieRoute
  '/enveloppes/classer': typeof EnveloppesClasserRoute
  '/enveloppes/creer': typeof EnveloppesCreerRoute
  '/enveloppes/details': typeof EnveloppesDetailsRoute
  '/enveloppes/modifier': typeof EnveloppesModifierRoute
  '/comptes/': typeof ComptesIndexRoute
  '/enveloppes/': typeof EnveloppesIndexRoute
  '/comptes/transferts/nouveau': typeof ComptesTransfertsNouveauRoute
  '/enveloppes/categorie/$nom': typeof EnveloppesCategorieNomRoute
  '/comptes/transferts/': typeof ComptesTransfertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/analyses': typeof AnalysesRoute
  '/depense': typeof DepenseRoute
  '/dettes': typeof DettesRoute
  '/journal': typeof JournalRoute
  '/outils': typeof OutilsRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/revenu': typeof RevenuRoute
  '/saisie': typeof SaisieRoute
  '/sauvegarde': typeof SauvegardeRoute
  '/synchronisation': typeof SynchronisationRoute
  '/comptes/$compte': typeof ComptesCompteRoute
  '/comptes/action': typeof ComptesActionRoute
  '/enveloppes/action': typeof EnveloppesActionRoute
  '/enveloppes/budgetisation': typeof EnveloppesBudgetisationRoute
  '/enveloppes/categories': typeof EnveloppesCategoriesRoute
  '/enveloppes/chronologie': typeof EnveloppesChronologieRoute
  '/enveloppes/classer': typeof EnveloppesClasserRoute
  '/enveloppes/creer': typeof EnveloppesCreerRoute
  '/enveloppes/details': typeof EnveloppesDetailsRoute
  '/enveloppes/modifier': typeof EnveloppesModifierRoute
  '/comptes': typeof ComptesIndexRoute
  '/enveloppes': typeof EnveloppesIndexRoute
  '/comptes/transferts/nouveau': typeof ComptesTransfertsNouveauRoute
  '/enveloppes/categorie/$nom': typeof EnveloppesCategorieNomRoute
  '/comptes/transferts': typeof ComptesTransfertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/analyses': typeof AnalysesRoute
  '/comptes': typeof ComptesRouteWithChildren
  '/depense': typeof DepenseRoute
  '/dettes': typeof DettesRoute
  '/enveloppes': typeof EnveloppesRouteWithChildren
  '/journal': typeof JournalRoute
  '/outils': typeof OutilsRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/revenu': typeof RevenuRoute
  '/saisie': typeof SaisieRoute
  '/sauvegarde': typeof SauvegardeRoute
  '/synchronisation': typeof SynchronisationRoute
  '/comptes/$compte': typeof ComptesCompteRoute
  '/comptes/action': typeof ComptesActionRoute
  '/comptes/transferts': typeof ComptesTransfertsRouteWithChildren
  '/enveloppes/action': typeof EnveloppesActionRoute
  '/enveloppes/budgetisation': typeof EnveloppesBudgetisationRoute
  '/enveloppes/categories': typeof EnveloppesCategoriesRoute
  '/enveloppes/chronologie': typeof EnveloppesChronologieRoute
  '/enveloppes/classer': typeof EnveloppesClasserRoute
  '/enveloppes/creer': typeof EnveloppesCreerRoute
  '/enveloppes/details': typeof EnveloppesDetailsRoute
  '/enveloppes/modifier': typeof EnveloppesModifierRoute
  '/comptes/': typeof ComptesIndexRoute
  '/enveloppes/': typeof EnveloppesIndexRoute
  '/comptes/transferts/nouveau': typeof ComptesTransfertsNouveauRoute
  '/enveloppes/categorie/$nom': typeof EnveloppesCategorieNomRoute
  '/comptes/transferts/': typeof ComptesTransfertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aide'
    | '/analyses'
    | '/comptes'
    | '/depense'
    | '/dettes'
    | '/enveloppes'
    | '/journal'
    | '/outils'
    | '/parametres'
    | '/planning'
    | '/revenu'
    | '/saisie'
    | '/sauvegarde'
    | '/synchronisation'
    | '/comptes/$compte'
    | '/comptes/action'
    | '/comptes/transferts'
    | '/enveloppes/action'
    | '/enveloppes/budgetisation'
    | '/enveloppes/categories'
    | '/enveloppes/chronologie'
    | '/enveloppes/classer'
    | '/enveloppes/creer'
    | '/enveloppes/details'
    | '/enveloppes/modifier'
    | '/comptes/'
    | '/enveloppes/'
    | '/comptes/transferts/nouveau'
    | '/enveloppes/categorie/$nom'
    | '/comptes/transferts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aide'
    | '/analyses'
    | '/depense'
    | '/dettes'
    | '/journal'
    | '/outils'
    | '/parametres'
    | '/planning'
    | '/revenu'
    | '/saisie'
    | '/sauvegarde'
    | '/synchronisation'
    | '/comptes/$compte'
    | '/comptes/action'
    | '/enveloppes/action'
    | '/enveloppes/budgetisation'
    | '/enveloppes/categories'
    | '/enveloppes/chronologie'
    | '/enveloppes/classer'
    | '/enveloppes/creer'
    | '/enveloppes/details'
    | '/enveloppes/modifier'
    | '/comptes'
    | '/enveloppes'
    | '/comptes/transferts/nouveau'
    | '/enveloppes/categorie/$nom'
    | '/comptes/transferts'
  id:
    | '__root__'
    | '/'
    | '/aide'
    | '/analyses'
    | '/comptes'
    | '/depense'
    | '/dettes'
    | '/enveloppes'
    | '/journal'
    | '/outils'
    | '/parametres'
    | '/planning'
    | '/revenu'
    | '/saisie'
    | '/sauvegarde'
    | '/synchronisation'
    | '/comptes/$compte'
    | '/comptes/action'
    | '/comptes/transferts'
    | '/enveloppes/action'
    | '/enveloppes/budgetisation'
    | '/enveloppes/categories'
    | '/enveloppes/chronologie'
    | '/enveloppes/classer'
    | '/enveloppes/creer'
    | '/enveloppes/details'
    | '/enveloppes/modifier'
    | '/comptes/'
    | '/enveloppes/'
    | '/comptes/transferts/nouveau'
    | '/enveloppes/categorie/$nom'
    | '/comptes/transferts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AideRoute: typeof AideRoute
  AnalysesRoute: typeof AnalysesRoute
  ComptesRoute: typeof ComptesRouteWithChildren
  DepenseRoute: typeof DepenseRoute
  DettesRoute: typeof DettesRoute
  EnveloppesRoute: typeof EnveloppesRouteWithChildren
  JournalRoute: typeof JournalRoute
  OutilsRoute: typeof OutilsRoute
  ParametresRoute: typeof ParametresRoute
  PlanningRoute: typeof PlanningRoute
  RevenuRoute: typeof RevenuRoute
  SaisieRoute: typeof SaisieRoute
  SauvegardeRoute: typeof SauvegardeRoute
  SynchronisationRoute: typeof SynchronisationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depense': {
      id: '/depense'
      path: '/depense'
      fullPath: '/depense'
      preLoaderRoute: typeof DepenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dettes': {
      id: '/dettes'
      path: '/dettes'
      fullPath: '/dettes'
      preLoaderRoute: typeof DettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enveloppes': {
      id: '/enveloppes'
      path: '/enveloppes'
      fullPath: '/enveloppes'
      preLoaderRoute: typeof EnveloppesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils': {
      id: '/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof OutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenu': {
      id: '/revenu'
      path: '/revenu'
      fullPath: '/revenu'
      preLoaderRoute: typeof RevenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie': {
      id: '/saisie'
      path: '/saisie'
      fullPath: '/saisie'
      preLoaderRoute: typeof SaisieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauvegarde': {
      id: '/sauvegarde'
      path: '/sauvegarde'
      fullPath: '/sauvegarde'
      preLoaderRoute: typeof SauvegardeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synchronisation': {
      id: '/synchronisation'
      path: '/synchronisation'
      fullPath: '/synchronisation'
      preLoaderRoute: typeof SynchronisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes/': {
      id: '/comptes/'
      path: '/'
      fullPath: '/comptes/'
      preLoaderRoute: typeof ComptesIndexRouteImport
      parentRoute: typeof ComptesRoute
    }
    '/comptes/$compte': {
      id: '/comptes/$compte'
      path: '/$compte'
      fullPath: '/comptes/$compte'
      preLoaderRoute: typeof ComptesCompteRouteImport
      parentRoute: typeof ComptesRoute
    }
    '/comptes/action': {
      id: '/comptes/action'
      path: '/action'
      fullPath: '/comptes/action'
      preLoaderRoute: typeof ComptesActionRouteImport
      parentRoute: typeof ComptesRoute
    }
    '/comptes/transferts': {
      id: '/comptes/transferts'
      path: '/transferts'
      fullPath: '/comptes/transferts'
      preLoaderRoute: typeof ComptesTransfertsRouteImport
      parentRoute: typeof ComptesRoute
    }
    '/enveloppes/': {
      id: '/enveloppes/'
      path: '/'
      fullPath: '/enveloppes/'
      preLoaderRoute: typeof EnveloppesIndexRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/action': {
      id: '/enveloppes/action'
      path: '/action'
      fullPath: '/enveloppes/action'
      preLoaderRoute: typeof EnveloppesActionRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/budgetisation': {
      id: '/enveloppes/budgetisation'
      path: '/budgetisation'
      fullPath: '/enveloppes/budgetisation'
      preLoaderRoute: typeof EnveloppesBudgetisationRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/categories': {
      id: '/enveloppes/categories'
      path: '/categories'
      fullPath: '/enveloppes/categories'
      preLoaderRoute: typeof EnveloppesCategoriesRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/chronologie': {
      id: '/enveloppes/chronologie'
      path: '/chronologie'
      fullPath: '/enveloppes/chronologie'
      preLoaderRoute: typeof EnveloppesChronologieRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/classer': {
      id: '/enveloppes/classer'
      path: '/classer'
      fullPath: '/enveloppes/classer'
      preLoaderRoute: typeof EnveloppesClasserRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/creer': {
      id: '/enveloppes/creer'
      path: '/creer'
      fullPath: '/enveloppes/creer'
      preLoaderRoute: typeof EnveloppesCreerRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/details': {
      id: '/enveloppes/details'
      path: '/details'
      fullPath: '/enveloppes/details'
      preLoaderRoute: typeof EnveloppesDetailsRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/modifier': {
      id: '/enveloppes/modifier'
      path: '/modifier'
      fullPath: '/enveloppes/modifier'
      preLoaderRoute: typeof EnveloppesModifierRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/comptes/transferts/': {
      id: '/comptes/transferts/'
      path: '/'
      fullPath: '/comptes/transferts/'
      preLoaderRoute: typeof ComptesTransfertsIndexRouteImport
      parentRoute: typeof ComptesTransfertsRoute
    }
    '/comptes/transferts/nouveau': {
      id: '/comptes/transferts/nouveau'
      path: '/nouveau'
      fullPath: '/comptes/transferts/nouveau'
      preLoaderRoute: typeof ComptesTransfertsNouveauRouteImport
      parentRoute: typeof ComptesTransfertsRoute
    }
    '/enveloppes/categorie/$nom': {
      id: '/enveloppes/categorie/$nom'
      path: '/categorie/$nom'
      fullPath: '/enveloppes/categorie/$nom'
      preLoaderRoute: typeof EnveloppesCategorieNomRouteImport
      parentRoute: typeof EnveloppesRoute
    }
  }
}

interface ComptesTransfertsRouteChildren {
  ComptesTransfertsNouveauRoute: typeof ComptesTransfertsNouveauRoute
  ComptesTransfertsIndexRoute: typeof ComptesTransfertsIndexRoute
}

const ComptesTransfertsRouteChildren: ComptesTransfertsRouteChildren = {
  ComptesTransfertsNouveauRoute: ComptesTransfertsNouveauRoute,
  ComptesTransfertsIndexRoute: ComptesTransfertsIndexRoute,
}

const ComptesTransfertsRouteWithChildren =
  ComptesTransfertsRoute._addFileChildren(ComptesTransfertsRouteChildren)

interface ComptesRouteChildren {
  ComptesCompteRoute: typeof ComptesCompteRoute
  ComptesActionRoute: typeof ComptesActionRoute
  ComptesTransfertsRoute: typeof ComptesTransfertsRouteWithChildren
  ComptesIndexRoute: typeof ComptesIndexRoute
}

const ComptesRouteChildren: ComptesRouteChildren = {
  ComptesCompteRoute: ComptesCompteRoute,
  ComptesActionRoute: ComptesActionRoute,
  ComptesTransfertsRoute: ComptesTransfertsRouteWithChildren,
  ComptesIndexRoute: ComptesIndexRoute,
}

const ComptesRouteWithChildren =
  ComptesRoute._addFileChildren(ComptesRouteChildren)

interface EnveloppesRouteChildren {
  EnveloppesActionRoute: typeof EnveloppesActionRoute
  EnveloppesBudgetisationRoute: typeof EnveloppesBudgetisationRoute
  EnveloppesCategoriesRoute: typeof EnveloppesCategoriesRoute
  EnveloppesChronologieRoute: typeof EnveloppesChronologieRoute
  EnveloppesClasserRoute: typeof EnveloppesClasserRoute
  EnveloppesCreerRoute: typeof EnveloppesCreerRoute
  EnveloppesDetailsRoute: typeof EnveloppesDetailsRoute
  EnveloppesModifierRoute: typeof EnveloppesModifierRoute
  EnveloppesIndexRoute: typeof EnveloppesIndexRoute
  EnveloppesCategorieNomRoute: typeof EnveloppesCategorieNomRoute
}

const EnveloppesRouteChildren: EnveloppesRouteChildren = {
  EnveloppesActionRoute: EnveloppesActionRoute,
  EnveloppesBudgetisationRoute: EnveloppesBudgetisationRoute,
  EnveloppesCategoriesRoute: EnveloppesCategoriesRoute,
  EnveloppesChronologieRoute: EnveloppesChronologieRoute,
  EnveloppesClasserRoute: EnveloppesClasserRoute,
  EnveloppesCreerRoute: EnveloppesCreerRoute,
  EnveloppesDetailsRoute: EnveloppesDetailsRoute,
  EnveloppesModifierRoute: EnveloppesModifierRoute,
  EnveloppesIndexRoute: EnveloppesIndexRoute,
  EnveloppesCategorieNomRoute: EnveloppesCategorieNomRoute,
}

const EnveloppesRouteWithChildren = EnveloppesRoute._addFileChildren(
  EnveloppesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AideRoute: AideRoute,
  AnalysesRoute: AnalysesRoute,
  ComptesRoute: ComptesRouteWithChildren,
  DepenseRoute: DepenseRoute,
  DettesRoute: DettesRoute,
  EnveloppesRoute: EnveloppesRouteWithChildren,
  JournalRoute: JournalRoute,
  OutilsRoute: OutilsRoute,
  ParametresRoute: ParametresRoute,
  PlanningRoute: PlanningRoute,
  RevenuRoute: RevenuRoute,
  SaisieRoute: SaisieRoute,
  SauvegardeRoute: SauvegardeRoute,
  SynchronisationRoute: SynchronisationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
