/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as DepenseRouteImport } from './routes/depense'
import { Route as EnveloppesRouteImport } from './routes/enveloppes'
import { Route as OutilsRouteImport } from './routes/outils'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as RevenuRouteImport } from './routes/revenu'
import { Route as ComptesIndexRouteImport } from './routes/comptes.index'
import { Route as ComptesCompteRouteImport } from './routes/comptes.$compte'
import { Route as EnveloppesIndexRouteImport } from './routes/enveloppes.index'
import { Route as EnveloppesActionRouteImport } from './routes/enveloppes.action'
import { Route as EnveloppesBudgetisationRouteImport } from './routes/enveloppes.budgetisation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const DepenseRoute = DepenseRouteImport.update({
  id: '/depense',
  path: '/depense',
  getParentRoute: () => rootRouteImport,
} as any)
const EnveloppesRoute = EnveloppesRouteImport.update({
  id: '/enveloppes',
  path: '/enveloppes',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsRoute = OutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenuRoute = RevenuRouteImport.update({
  id: '/revenu',
  path: '/revenu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesIndexRoute = ComptesIndexRouteImport.update({
  id: '/comptes/',
  path: '/comptes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesCompteRoute = ComptesCompteRouteImport.update({
  id: '/comptes/$compte',
  path: '/comptes/$compte',
  getParentRoute: () => rootRouteImport,
} as any)
const EnveloppesIndexRoute = EnveloppesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesActionRoute = EnveloppesActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => EnveloppesRoute,
} as any)
const EnveloppesBudgetisationRoute = EnveloppesBudgetisationRouteImport.update({
  id: '/budgetisation',
  path: '/budgetisation',
  getParentRoute: () => EnveloppesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/analyses': typeof AnalysesRoute
  '/depense': typeof DepenseRoute
  '/enveloppes': typeof EnveloppesRouteWithChildren
  '/outils': typeof OutilsRoute
  '/parametres': typeof ParametresRoute
  '/revenu': typeof RevenuRoute
  '/comptes/$compte': typeof ComptesCompteRoute
  '/enveloppes/action': typeof EnveloppesActionRoute
  '/enveloppes/budgetisation': typeof EnveloppesBudgetisationRoute
  '/comptes/': typeof ComptesIndexRoute
  '/enveloppes/': typeof EnveloppesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/analyses': typeof AnalysesRoute
  '/depense': typeof DepenseRoute
  '/outils': typeof OutilsRoute
  '/parametres': typeof ParametresRoute
  '/revenu': typeof RevenuRoute
  '/comptes/$compte': typeof ComptesCompteRoute
  '/enveloppes/action': typeof EnveloppesActionRoute
  '/enveloppes/budgetisation': typeof EnveloppesBudgetisationRoute
  '/comptes': typeof ComptesIndexRoute
  '/enveloppes': typeof EnveloppesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/analyses': typeof AnalysesRoute
  '/depense': typeof DepenseRoute
  '/enveloppes': typeof EnveloppesRouteWithChildren
  '/outils': typeof OutilsRoute
  '/parametres': typeof ParametresRoute
  '/revenu': typeof RevenuRoute
  '/comptes/$compte': typeof ComptesCompteRoute
  '/enveloppes/action': typeof EnveloppesActionRoute
  '/enveloppes/budgetisation': typeof EnveloppesBudgetisationRoute
  '/comptes/': typeof ComptesIndexRoute
  '/enveloppes/': typeof EnveloppesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aide'
    | '/analyses'
    | '/depense'
    | '/enveloppes'
    | '/outils'
    | '/parametres'
    | '/revenu'
    | '/comptes/$compte'
    | '/enveloppes/action'
    | '/enveloppes/budgetisation'
    | '/comptes/'
    | '/enveloppes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aide'
    | '/analyses'
    | '/depense'
    | '/outils'
    | '/parametres'
    | '/revenu'
    | '/comptes/$compte'
    | '/enveloppes/action'
    | '/enveloppes/budgetisation'
    | '/comptes'
    | '/enveloppes'
  id:
    | '__root__'
    | '/'
    | '/aide'
    | '/analyses'
    | '/depense'
    | '/enveloppes'
    | '/outils'
    | '/parametres'
    | '/revenu'
    | '/comptes/$compte'
    | '/enveloppes/action'
    | '/enveloppes/budgetisation'
    | '/comptes/'
    | '/enveloppes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AideRoute: typeof AideRoute
  AnalysesRoute: typeof AnalysesRoute
  DepenseRoute: typeof DepenseRoute
  EnveloppesRoute: typeof EnveloppesRouteWithChildren
  OutilsRoute: typeof OutilsRoute
  ParametresRoute: typeof ParametresRoute
  RevenuRoute: typeof RevenuRoute
  ComptesCompteRoute: typeof ComptesCompteRoute
  ComptesIndexRoute: typeof ComptesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depense': {
      id: '/depense'
      path: '/depense'
      fullPath: '/depense'
      preLoaderRoute: typeof DepenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enveloppes': {
      id: '/enveloppes'
      path: '/enveloppes'
      fullPath: '/enveloppes'
      preLoaderRoute: typeof EnveloppesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils': {
      id: '/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof OutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenu': {
      id: '/revenu'
      path: '/revenu'
      fullPath: '/revenu'
      preLoaderRoute: typeof RevenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes/': {
      id: '/comptes/'
      path: '/comptes'
      fullPath: '/comptes/'
      preLoaderRoute: typeof ComptesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes/$compte': {
      id: '/comptes/$compte'
      path: '/comptes/$compte'
      fullPath: '/comptes/$compte'
      preLoaderRoute: typeof ComptesCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enveloppes/': {
      id: '/enveloppes/'
      path: '/'
      fullPath: '/enveloppes/'
      preLoaderRoute: typeof EnveloppesIndexRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/action': {
      id: '/enveloppes/action'
      path: '/action'
      fullPath: '/enveloppes/action'
      preLoaderRoute: typeof EnveloppesActionRouteImport
      parentRoute: typeof EnveloppesRoute
    }
    '/enveloppes/budgetisation': {
      id: '/enveloppes/budgetisation'
      path: '/budgetisation'
      fullPath: '/enveloppes/budgetisation'
      preLoaderRoute: typeof EnveloppesBudgetisationRouteImport
      parentRoute: typeof EnveloppesRoute
    }
  }
}

interface EnveloppesRouteChildren {
  EnveloppesActionRoute: typeof EnveloppesActionRoute
  EnveloppesBudgetisationRoute: typeof EnveloppesBudgetisationRoute
  EnveloppesIndexRoute: typeof EnveloppesIndexRoute
}

const EnveloppesRouteChildren: EnveloppesRouteChildren = {
  EnveloppesActionRoute: EnveloppesActionRoute,
  EnveloppesBudgetisationRoute: EnveloppesBudgetisationRoute,
  EnveloppesIndexRoute: EnveloppesIndexRoute,
}

const EnveloppesRouteWithChildren = EnveloppesRoute._addFileChildren(
  EnveloppesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AideRoute: AideRoute,
  AnalysesRoute: AnalysesRoute,
  DepenseRoute: DepenseRoute,
  EnveloppesRoute: EnveloppesRouteWithChildren,
  OutilsRoute: OutilsRoute,
  ParametresRoute: ParametresRoute,
  RevenuRoute: RevenuRoute,
  ComptesCompteRoute: ComptesCompteRoute,
  ComptesIndexRoute: ComptesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
